version: 2
updates:
  - package-ecosystem: "bun"
    directory: "web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
